[package]
name = "carbonium"
version = "0.1.0"
edition = "2024"

[dependencies]
common-game = { git = "ssh://git@github.com/unitn-ap-2025/common.git", branch="release-candidate" }
lazy_static = "1.5.0"
crossbeam-channel = "0.5.15"

[dev-dependencies]
ntest = "*"
